name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request: 
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      test:
        required: false
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        
      - name: Build
        run: go build -o vdsapi -v ./..

      - name: Test
        run: go test -v ./..

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: vdsapi
          path: vdsapi
